services:
  app:
    image: ghcr.io/jesperrichert/assetory:latest
    volumes:
      - "./storage/:/app/storage/"
    ports:
      - "4000:3000"
    depends_on:
      postgres:
        condition: service_healthy
        required: true
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "assetory"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
